//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int cli_dni { get; set; }
        public string cli_nombre { get; set; }
        public Nullable<int> cli_edad { get; set; }
        public string cli_sexo { get; set; }
        public string cli_universidad { get; set; }
        public string cli_distrito { get; set; }
        public string cli_correo { get; set; }
        public Nullable<int> codigo_sala { get; set; }
        public string cli_banda { get; set; }
    }
}
