//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int cli_dni { get; set; }
        public string cli_nombre { get; set; }
        public Nullable<int> cli_edad { get; set; }
        public string cli_sexo { get; set; }
        public string cli_universidad { get; set; }
        public string cli_distrito { get; set; }
        public string cli_correo { get; set; }
        public Nullable<int> codigo_sala { get; set; }
        public string cli_banda { get; set; }
        public Nullable<System.DateTime> cli_ultimareserva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
