//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControladoraInstrumento
    {
        public int id_controlador { get; set; }
        public Nullable<System.DateTime> fecha_controlador { get; set; }
        public string horainicial_controlador { get; set; }
        public string horafinal_controlador { get; set; }
        public string estado_controlador { get; set; }
        public Nullable<int> identficiador_instrumento { get; set; }
    }
}
