//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControladoraInstrumento
    {
        public int id_controlador { get; set; }
        public Nullable<System.DateTime> fecha_controlador { get; set; }
        public string horainicial_controlador { get; set; }
        public string horafinal_controlador { get; set; }
        public string estado_controlador { get; set; }
        public Nullable<int> identficiador_instrumento { get; set; }
    }
}
