//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReserva
    {
        public int id_detalle { get; set; }
        public Nullable<int> id2_reserva { get; set; }
        public string nombre_cliente { get; set; }
        public string horario_reserva { get; set; }
        public string nom_sala { get; set; }
        public Nullable<int> reinstrumento_codigo { get; set; }
    }
}
