//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReserva
    {
        public int id_detalle { get; set; }
        public Nullable<int> id2_reserva { get; set; }
        public string nombre_cliente { get; set; }
        public string horario_reserva { get; set; }
        public string nom_sala { get; set; }
        public Nullable<int> reinstrumento_codigo { get; set; }
    
        public virtual Reserva Reserva { get; set; }
        public virtual ReservaInstrumento ReservaInstrumento { get; set; }
    }
}
