//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int id_reserva { get; set; }
        public Nullable<int> cliente_dni { get; set; }
        public Nullable<int> codigo_horario { get; set; }
        public Nullable<int> codigo2_sala { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
    }
}
