//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaInstrumento
    {
        public int id_reservainstrumento { get; set; }
        public Nullable<int> id_reservarel { get; set; }
        public Nullable<int> id_instrumento { get; set; }
    }
}
